# Generated by Django 4.1.1 on 2023-01-09 05:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, max_length=800)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('image1', models.ImageField(upload_to='images/products')),
                ('image2', models.ImageField(upload_to='images/products')),
                ('image3', models.ImageField(upload_to='images/products')),
                ('image4', models.ImageField(upload_to='images/products')),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('have_size', models.BooleanField(default=False)),
                ('nonsizestock', models.IntegerField(blank=True, default=100, validators=[django.core.validators.MinValueValidator(0)])),
                ('sizestockS', models.IntegerField(blank=True, default=100, validators=[django.core.validators.MinValueValidator(0)])),
                ('sizestockM', models.IntegerField(blank=True, default=100, validators=[django.core.validators.MinValueValidator(0)])),
                ('sizestockL', models.IntegerField(blank=True, default=100, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('discount_price', models.IntegerField(blank=True, default=0, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Productoffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_offer', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Categoryoffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='category_offer', to='category.category')),
            ],
        ),
    ]
